/** 
 * A1 : Extracting IPv4 Addresses from Noisy Text
 * Drew Franke
 * All code below this header was generated by OpenAI's GPT-5.6 Luna
 * For more information on AI usage, please see the AI usage and disclosure document
 * on the github repository - https://github.com/1v9inyourpeak/EECS581_A1/blob/main/AI%20usage%20%26%20disclosure.MD
*/

#include <iostream>
#include <string>
#include <cctype>

using namespace std;

// Returns true if a valid address was found, false otherwise.
// On success: outAddress holds the 32-bit value,
// and outPort holds the port number, or -1 if no port was present.
// On failure: outAddress is set to 0 and outPort is set to -1.
bool extractIPv4(const std::string& str, unsigned long& outAddress, int& outPort)
{
    // Required failure values
    outAddress = 0;
    outPort = -1;

    size_t i = 0;

    while (i < str.length())
    {
        // Skip garbage characters.
        if (!(isdigit(static_cast<unsigned char>(str[i])) ||
              str[i] == '.' ||
              str[i] == ':'))
        {
            ++i;
            continue;
        }

        // Find the end of this candidate token.
        // A token consists ONLY of digits, periods, and colons.
        size_t start = i;

        while (i < str.length() &&
               (isdigit(static_cast<unsigned char>(str[i])) ||
                str[i] == '.' ||
                str[i] == ':'))
        {
            ++i;
        }

        size_t end = i;

        // ------------------------------------------------------------
        // Parse the candidate token.
        // Grammar:
        //   octet.octet.octet.octet[:port]
        // ------------------------------------------------------------

        size_t pos = start;
        unsigned long address = 0;
        int port = -1;
        int octetCount = 0;
        bool valid = true;

        for (int octetIndex = 0; octetIndex < 4; ++octetIndex)
        {
            // An octet must contain at least one digit.
            if (pos >= end || !isdigit(static_cast<unsigned char>(str[pos])))
            {
                valid = false;
                break;
            }

            // Check for a leading zero.
            size_t digitStart = pos;

            if (str[pos] == '0')
            {
                ++pos;

                // "00", "01", etc. are invalid.
                if (pos < end &&
                    isdigit(static_cast<unsigned char>(str[pos])))
                {
                    valid = false;
                    break;
                }
            }
            else
            {
                // Accumulate the octet manually.
                int value = 0;
                int digitCount = 0;

                while (pos < end &&
                       isdigit(static_cast<unsigned char>(str[pos])))
                {
                    value = value * 10 + (str[pos] - '0');
                    ++digitCount;
                    ++pos;

                    // An octet may contain at most 3 digits.
                    if (digitCount > 3)
                    {
                        valid = false;
                        break;
                    }
                }

                if (!valid || value > 255)
                {
                    valid = false;
                    break;
                }

                // Build the 32-bit address manually.
                address = address * 256UL +
                          static_cast<unsigned long>(value);

                ++octetCount;

                // A period is required after the first 3 octets.
                if (octetIndex < 3)
                {
                    if (pos >= end || str[pos] != '.')
                    {
                        valid = false;
                        break;
                    }

                    ++pos;
                }

                continue;
            }

            // This handles the special case where the octet is exactly 0.
            if (pos == digitStart + 1)
            {
                address = address * 256UL;
                ++octetCount;

                if (octetIndex < 3)
                {
                    if (pos >= end || str[pos] != '.')
                    {
                        valid = false;
                        break;
                    }

                    ++pos;
                }
            }
        }

        if (!valid || octetCount != 4)
            continue;

        // ------------------------------------------------------------
        // Optional port
        // ------------------------------------------------------------

        if (pos < end)
        {
            // If anything remains, it must be a colon.
            if (str[pos] != ':')
                continue;

            ++pos;

            // A colon must be followed by at least one digit.
            if (pos >= end ||
                !isdigit(static_cast<unsigned char>(str[pos])))
            {
                continue;
            }

            // Leading zero rule for port.
            if (str[pos] == '0')
            {
                ++pos;

                // "00", "01", etc. are invalid.
                if (pos < end &&
                    isdigit(static_cast<unsigned char>(str[pos])))
                {
                    continue;
                }

                port = 0;
            }
            else
            {
                int portValue = 0;
                int digitCount = 0;

                while (pos < end &&
                       isdigit(static_cast<unsigned char>(str[pos])))
                {
                    portValue = portValue * 10 + (str[pos] - '0');
                    ++digitCount;
                    ++pos;

                    // Ports may contain at most 5 digits.
                    if (digitCount > 5)
                        break;
                }

                if (digitCount == 0 ||
                    digitCount > 5 ||
                    portValue > 65535)
                {
                    continue;
                }

                port = portValue;
            }
        }

        // Nothing except the optional port may remain.
        if (pos != end)
            continue;

        // We found a completely valid token.
        outAddress = address;
        outPort = port;
        return true;
    }

    return false;
}


int main()
{
    string input;

    while (true)
    {
        cout << "Enter a line of text (END to quit): ";

        getline(cin, input);

        if (input == "END")
        {
            cout << "Program terminated." << endl;
            break;
        }

        unsigned long address;
        int port;

        if (extractIPv4(input, address, port))
        {
            // Recover the four octets from the 32-bit value
            // for display.
            unsigned int a = static_cast<unsigned int>(
                (address >> 24) & 255UL
            );

            unsigned int b = static_cast<unsigned int>(
                (address >> 16) & 255UL
            );

            unsigned int c = static_cast<unsigned int>(
                (address >> 8) & 255UL
            );

            unsigned int d = static_cast<unsigned int>(
                address & 255UL
            );

            cout << "Extracted IPv4 address: "
                 << a << "." << b << "." << c << "." << d
                 << " (decimal value: " << address
                 << ", port: ";

            if (port == -1)
                cout << "none";
            else
                cout << port;

            cout << ")" << endl;
        }
        else
        {
            cout << "No valid IPv4 address found." << endl;
        }
    }

    return 0;
}
